train:
  limit: 2
  _target_: src.datasets.SSDataset
  encoder: ${encoder}
  part: "val"
  audio_dir: /Users/andreypetukhov/Documents/Машинное-обучение/AVSS/dla_dataset/audio
  video_dir: /Users/andreypetukhov/Documents/Машинное-обучение/AVSS/dla_dataset/mouths
  embedding_dir: /Users/andreypetukhov/Documents/Машинное-обучение/AVSS/dla_dataset/embeddings
  instance_transforms: ${transforms.instance_transforms.train}

val:
  limit: 2
  _target_: src.datasets.SSDataset
  encoder: ${encoder}
  part: "val"
  audio_dir: /Users/andreypetukhov/Documents/Машинное-обучение/AVSS/dla_dataset/audio
  video_dir: /Users/andreypetukhov/Documents/Машинное-обучение/AVSS/dla_dataset/mouths
  embedding_dir: /Users/andreypetukhov/Documents/Машинное-обучение/AVSS/dla_dataset/embeddings
  instance_transforms: ${transforms.instance_transforms.inference}