encoder:
  _target_: src.encoders.RTFS
  n_fft: 256
  hop_length: 128

train:
  limit: 2
  _target_: src.datasets.SSDataset
  encoder: ${encoder}
  part: "val"
  audio_dir: /home/teasgen/dla/speech_separation/dla_dataset/audio
  video_dir: /home/teasgen/dla/speech_separation/dla_dataset/mouths
  embedding_dir: /home/teasgen/dla/speech_separation/dla_dataset/embeddings
  instance_transforms: ${transforms.instance_transforms.train}

val:
  limit: 2
  _target_: src.datasets.SSDataset
  encoder: ${encoder}
  part: "val"
  audio_dir: /home/teasgen/dla/speech_separation/dla_dataset/audio
  video_dir: /home/teasgen/dla/speech_separation/dla_dataset/mouths
  embedding_dir: /home/teasgen/dla/speech_separation/dla_dataset/embeddings
  instance_transforms: ${transforms.instance_transforms.inference}