train:
  limit: 10
  _target_: src.datasets.SSDatasetKaggle
  part: "val"
  audio_dir: /kaggle/input/dla_dataset/audio
  video_dir: /kaggle/input/dla_dataset/mouths
  instance_transforms: ${transforms.instance_transforms.train}
val:
  limit: 10
  _target_: src.datasets.SSDatasetKaggle
  part: "val"
  audio_dir: /kaggle/input/dla_dataset/audio
  video_dir: /kaggle/input/dla_dataset/mouths
  instance_transforms: ${transforms.instance_transforms.inference}