train:
  limit: 1
  _target_: src.datasets.SSDataset
  part: "train"
  audio_dir: /kaggle/input/dla-hw2/dla_dataset/audio
  video_dir: /kaggle/input/dla-hw2/dla_dataset/mouths
  instance_transforms: ${transforms.instance_transforms.train}
val:
  limit: 1
  _target_: src.datasets.SSDataset
  part: "val"
  audio_dir: /kaggle/input/dla-hw2/dla_dataset/audio
  video_dir: /kaggle/input/dla-hw2/dla_dataset/mouths
  instance_transforms: ${transforms.instance_transforms.inference}