val:
  _target_: src.datasets.SSDataset
  part: "val"
  audio_dir: /home/teasgen/dla/speech_separation/dla_dataset/audio
  embedding_dir: /home/teasgen/dla/speech_separation/dla_dataset/embd2
  instance_transforms: ${transforms.instance_transforms.inference}