train:
  _target_: src.datasets.SSDatasetKaggle
  part: "train"
  audio_dir: /kaggle/input/dla-hw2-extended/dla_dataset/audio
  video_dir: /kaggle/input/dla-hw2-extended/dla_dataset/mouths
  embedding_dir: /kaggle/input/dla-hw2-extended/dla_dataset/embeddings
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.SSDatasetKaggle
  part: "val"
  audio_dir: /kaggle/input/dla-hw2-extended/dla_dataset/audio
  video_dir: /kaggle/input/dla-hw2-extended/dla_dataset/mouths
  embedding_dir: /kaggle/input/dla-hw2-extended/dla_dataset/embeddings
  instance_transforms: ${transforms.instance_transforms.inference}