train: # metrics that are calculated during training
  - _target_: src.metrics.SISDRMetric
    name: "SISDRMetric"
    device: cpu
inference: # metrics that are calculated during inference (eval)
  - _target_: src.metrics.SISNRMetric
    name: "SISNRMetric"
    device: cpu
