_target_: src.model.DPTNAVWavEncDec
num_features: 128
video_emb_size: 512
hidden_video: 128
kernel_size_enc: 7
hidden_dim: 128
num_blocks: 6
chunk_size: 150
step_size: 75
num_heads: 4
dropout: 0.1
bidir: True
