_target_: src.model.RTFSNetwork
R: 4
n_fft: 256
hop_length: 128
audio_out_channels: 256
video_embed_size: 512
reduced_channels: 64
audio_kernel_size: 4
video_kernel_size: 3
num_upsamples: 3
num_attn_heads: 4
